version: '3'
services:
  web:
    build: .
    command: npm start
    container_name: static-contact-validation
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
    ports:
      - "3000:3000"
